### ISSUE TITLE
Stack (...) is in CREATE_FAILED state and can not be updated.

### ISSUE THREAD

**Issue by belfz** [dawson-org/dawson-cli#154]
Got this while trying to deploy the simple function (first example from dawson's docs):

```
 ↓ running pre-deploy hook [skipped]
 ✔ validating configuration
 ↓ running pre-deploy hook [skipped]
 ✔ validating configuration
 ✔ checking prerequisites
 ✔ creating bundle
 ✔ generating template
 ↓ removing stack policy [skipped]
 ✖ requesting changeset
   → Stack:arn:aws:cloudformation:us-west-2:125826905630:stack/dawson-tutorialDefault/d8434070-0fdb-11e7-b5d8-50a68a201256 is in CREATE_FAILED state and can not …
   waiting for stack update to complete
   setting stack policy
   running post-deploy hook
   uploading assets
dawson internal error: Stack:arn:aws:cloudformation:us-west-2:125826905630:stack/dawson-tutorialDefault/d8434070-0fdb-11e7-b5d8-50a68a201256 is in CREATE_FAILED s
tate and can not be updated.
ValidationError: Stack:arn:aws:cloudformation:us-west-2:125826905630:stack/dawson-tutorialDefault/d8434070-0fdb-11e7-b5d8-50a68a201256 is in CREATE_FAILED state a
nd can not be updated.
    at Request.extractError (/usr/local/lib/node_modules/dawson/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/usr/local/lib/node_modules/dawson/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/dawson/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/dawson/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/usr/local/lib/node_modules/dawson/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/dawson/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/dawson/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/dawson/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/dawson/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/usr/local/lib/node_modules/dawson/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
Please report this bug: https://github.com/dawson-org/dawson-cli/issues
```

**Comment by brandoncorbin** [comment]
I'm seeing this error too. 

Mac 10.11.6
Node v6.10.1

**Comment by lusentis** [comment]
Sorry, we're investigating an issue most likely related to an internal AWS update. We're seeing failed stack creation and updates since this morning (without any change to dawson or our app code). 

Unfortunately, I'll be traveling until Sunday, so I can't check this; pinging @alexcasalboni and @giacomo which may help. 

Updates asap.

**Comment by lusentis** [comment]
Digging into the issue, starting this morning, the following IAM Trust Policy contains a Syntax Error:

An error occurred: Syntax errors in policy: {"Version":"2012-10-17","Statement":[{"Action":["sts:AssumeRole"],"Effect":"Allow","Principal":{"Service":["lambda.amazonaws.com"],"AWS":["arn:aws:iam::24310286XXXX:root"]}}]}

**Comment by lusentis** [comment]
While this policy is equivalent and valid:

{"Version":"2012-10-17","Statement":[
{"Action":["sts:AssumeRole"],"Effect":"Allow","Principal":{"Service":["lambda.amazonaws.com"] }}
, 
{"Action":["sts:AssumeRole"],"Effect":"Allow","Principal":{"AWS":["arn:aws:iam::24310286XXXX:root"]}} 
]}

I have simply split the two "principals" in different statements. 
If someone could update and create a PR this will solve the issue:
https://github.com/dawson-org/dawson-cli/blob/master/src/factories/cf_lambda.js
The functions involved are: templateLambdaExecutionRole and extraTrustPrincipals


Deploys in production environments (where NODE_ENV is production) should not be affected. 

@lcasartelli can you confirm that this solution works for you? Thansk

**Comment by lusentis** [comment]
Or... That might not be the real problem. I'm from my smartphone and can't properly check everything. 

One aws forum post from 2014 says that all policies suddenly stopped working when using wrong line endings. Maybe our current issue is similar. 

Copy and pasting the policy above in a iam role trust policy returns a Syntax Error. Using the second one, with split statements, don't.

**Comment by rakistner** [comment]
I am experiencing the same issue, even doing the example deploy from the docs.
Dawson 0.23.3
Node v 7.6
OSX 10.10.5

**Comment by goyney** [comment]
I am also experiencing the same issue.

**Comment by sayjava** [comment]
Same here, sa,e problem

**Comment by rakistner** [comment]
It seems this is a IAM roles issue. I was unable to successfully use the cli with anything other than giving a user the AdministratorAccess role. PowerUserAccess and individual policy attachments for each service in the build (such as LambdaInvokeFullAccess) did not work. So easy user fix is to create a non-admin user with admin access, but obviously in the long term this is not ideal. Have not identified where in the source code this might be restricted yet.

**Comment by lusentis** [comment]
Ok, I'm sorry for the issues you're experiencing. I thought this was related to an issue we're having internally: on 23rd March since early morning (GMT+1) stack creation and updates were failing due to an internal AWS issue related to IAM Roles.
I initially thought that such issue was related to yours, probably incorrectly. The AWS internal issue now seems to be fixed and deploys are working again as expected.

Unfortunately, errors which happen during the Create step are not as informative as errors happening during a Stack Update operation (we'll fix).

@rakistner the CLI uses CloudFormation to create resources, including, for example, IAM Roles. CloudFormation will then need the permission to call operations such as IAM::CreateRole etc. The easiest way to ensure that every update will succeed is to use an AdministratorAccess policy.
(You won't find any call to iam::CreateRole in dawson's code, because this operation is called internally by CloudFormation.)

Quoting an HN comment of mine:
> dawson will soon switch to using an AWS CloudFormation Service Role, which allows us to require users to grant fine-grained permissions. We will then provide a copy-pasteable Policy for users to set, and update the documentation accordingly.
> Currently, since CloudFormations runs with the CLI user's AWS Credentials, such user needs to be granted the permission to do every action, including, for example, managing DynamoDB Tables, S3 Buckets etc...
> Also, imagine you're adding an S3 Bucket as a custom resource to your app. dawson will create such S3 Bucket using CloudFormation; CloudFormation needs to be run by a user with S3::CreateBucket permission. This applies for each resource managed by dawson/CloudFormation.
> NONE of your App's code will run using such "AdministratorAccess" policies. Each function will run in its own iam:Role with limited permissions defined by the developer.
> The AdministratorAccess is currently required only for the CLI but, as said in my previous comment, we'll eventually move to using a Service Role and providing a more restrictive policy.

This will be our top priority after merging Python support later this week.

**Comment by lusentis** [comment]
I'd appreciate knowing if you're able to perform a deploy in these days (no dawson update was published to `npm` since the issue appeared to be internal to AWS).
If not, you could please provide the error message that the [AWS CloudFormation Console](https://console.aws.amazon.com/cloudformation/home) displays?

Thanks for your feedback

**Comment by rakistner** [comment]
I am able to deploy successfully today. I did miss that step in the docs, but it's definitely not because it's not written clearly haha. The enhancement from your comment sounds like what I expected to happen. Thanks for getting back to us so quickly!

**Comment by lusentis** [comment]
Thank you!

> I did miss that step in the docs, but it's definitely not because it's not written clearly haha

It's always [system's fault](https://www.amazon.com/Design-Everyday-Things-Revised-Expanded/dp/0465050654/ref=pd_sbs_14_t_0/162-4019768-4455658?_encoding=UTF8&psc=1&refRID=GB7C1WJ6AKEHDDJPFGTG) ;)

We'll for sure improve the error message, and maybe attempt to validate credentials. I'm leaving this issue open.

Thanks for your feedback,

**Comment by lusentis** [comment]
I'm closing this issue since, at this point, we can confirm it was an AWS internal error and I'm resuming the work on #159.
